#!/bin/bash

# Compile everything without making object files first, 
# because that breaks gsl for som eunknown reason.
gcc src/main.c src/math.c src/tui.c src/outFiles.c src/helium3.c -o build/helium3 -Wall -Wextra -lgsl -Iinclude -I/usr/local/include -IOSspecific -L/usr/local/lib
